---
- hosts: webservers
  become: true

  vars:
    ansible_become_pass: jenkins

  tasks:
    - name: install tomcat
      ansible.builtin.yum:
        name: 
         - tomcat
         - tomcat-webapps
        state: installed
    - name: start and enable tomcat
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: yes
...
